# Generated by Django 2.1.4 on 2018-12-13 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='date_of_visit',
            field=models.DateTimeField(null=True, verbose_name='date published'),
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateTimeField(null=True, verbose_name='date published'),
        ),
    ]
