# Generated by Django 2.0.5 on 2018-12-18 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20181218_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='clinic',
            field=models.TextField(),
        ),
    ]
