# Generated by Django 2.1.4 on 2018-12-13 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20181213_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='time_of_visit',
            field=models.TimeField(default='time'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_of_visit',
            field=models.DateField(),
        ),
    ]
